### ISSUE TITLE
can't run bot

### ISSUE THREAD

**Issue by Nord1cWarr1or** [dkzhen/piggy-bot#3]
```
> piggy-bot@1.0.0 start
> node index.js

node:events:498
throw er; // Unhandled 'error' event
^

Error: listen EACCES: permission denied 0.0.0.0:104
at Server.setupListenHandle [as _listen2] (node:net:1880:21)
at listenInCluster (node:net:1959:12)
at Server.listen (node:net:2061:7)
at Function.listen (/home/cs/Temp/piggy-bot/node_modules/express/lib/application.js:635:24)
at Object.<anonymous> (/home/cs/Temp/piggy-bot/index.js:33:5)
at Module._compile (node:internal/modules/cjs/loader:1546:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
at Module.load (node:internal/modules/cjs/loader:1317:32)
at Module._load (node:internal/modules/cjs/loader:1127:12)
at TracingChannel.traceSync (node:diagnostics_channel:315:14)
Emitted 'error' event on Server instance at:
at emitErrorNT (node:net:1938:8)
at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
code: 'EACCES',
errno: -13,
syscall: 'listen',
address: '0.0.0.0',
port: 104
}

Node.js v22.7.0
```

**Comment by Nord1cWarr1or** [comment]
I had to run it as sudo
